Validation phase: True
Namespace(iter_possible_stop=999999, BATCH_SIZE=4, NUM_OF_DATALOADER_WORKERS=10, NUM_TRAIN_ITERS_BETWEEN_PRUNINGS=1, SAVE_DIR='SegNet', PATH_TO_DATA='./sclera_data', is_test_run=True, pruning_phase=True, pbop=True, e_ix=3, mti=1000000000.0, map=2, nept=1, pnkao=50, nftp=1, rn='flops_num', ptp=0.02)
path to file: ./sclera_data
summary for train
valid images: 1288
summary for val
valid images: 344
summary for test
valid images: 208
train dataset len: 30
val dataset len: 30
test dataset len: 30
train dataloader num of batches: 8
val dataloader num of batches: 8
test dataloader num of batches: 8
Device: cuda
Traceback (most recent call last):
  File "/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/segnet_main.py", line 755, in <module>
    raise ValueError("This is the end of the script. The rest is just for reference.")
ValueError: This is the end of the script. The rest is just for reference.
