Validation phase: False
Namespace(iter_possible_stop=0, BATCH_SIZE=4, NUM_OF_DATALOADER_WORKERS=10, NUM_TRAIN_ITERS_BETWEEN_PRUNINGS=1, SAVE_DIR='UNet', PATH_TO_DATA='./sclera_data', is_test_run=False, pruning_phase=False, pbop=False, e_ix=3, mti=2, map=1000000000.0, nept=1, pnkao=20, nftp=1, rn='flops_num', ptp=0.01)
path to file: ./sclera_data
summary for train
valid images: 1288
summary for val
valid images: 344
summary for test
valid images: 208
train dataset len: 1288
val dataset len: 344
test dataset len: 208
train dataloader num of batches: 322
val dataloader num of batches: 86
test dataloader num of batches: 52
Device: cuda
0 trainings have been done without error stopping.
                        Best k models are kept. (possibly (k+1) models are kept if one of the worse models is the last model we have).
                        Enter s to save the model and re-ask for input.
                        Enter g to show the graph of the model and re-ask for input.
                        Enter r to trigger show_results() and re-ask for input.
                        Enter a number to reset in how many trainings we ask you this again, and re-ask for input.
                        Enter p to prune anyways (in production code, that is commented out, so the program will simply stop).
                        Press Enter to continue training.
                        Enter any other key to stop.
Copied UNet_3_2_just_pruned.pth to ./UNet/safety_copies/actual_safety_copies
File UNet_2_2_special_save.pth already exists in safety copies, skipping.
File UNet_1_2.pth already exists in safety copies, skipping.
File UNet_0_0_special_save.pth already exists in safety copies, skipping.
File UNet_1_1.pth already exists in safety copies, skipping.
CSV file ./UNet/safety_copies/safety_copies_2_special_save.csv already exists. Please choose a different name or handle the existing file.
Traceback (most recent call last):
  File "/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/main.py", line 933, in <module>
    train_automatically(model_wrapper, main_save_path, validation_stop, max_training_iters=max_train_iters, max_auto_prunings=max_auto_prunings, train_iter_possible_stop=iter_possible_stop, pruning_phase=is_pruning_ph, error_ix=err_ix,
  File "/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/training_support.py", line 398, in train_automatically
    training_logs, pruning_logs = perform_simple_save(model_wrapper, training_logs, pruning_logs, main_save_path, f"{train_iter}_special_save", curr_training_phase_serial_num)
  File "/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/training_support.py", line 276, in perform_simple_save
    training_logs.delete_all_but_best_k_models(3, model_wrapper)
  File "/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/training_support.py", line 169, in delete_all_but_best_k_models
    model_path = error[3]
TypeError: 'NoneType' object is not subscriptable
