Validation phase: False
Namespace(ips=999999, bs=4, nodw=10, ntibp=10, sd='UNet', ptd='./vein_sclera_data', is_test_run=True, pruning_phase=False, pbop=False, e_ix=3, mti=2, map=1000000000.0, nept=1, pnkao=20, nftp=1, rn='flops_num', ptp=0.01, tp=False, ifn=(0.5, 0.5, 0.5))
path to file: ./vein_sclera_data
summary for train
valid images: 89
summary for val
valid images: 27
summary for test
valid images: 12
train dataset len: 30
val dataset len: 27
test dataset len: 12
train dataloader num of batches: 8
val dataloader num of batches: 7
test dataloader num of batches: 3
Device: cuda
loss: 0.544743  [    4/   30]
loss: 0.538156  [    8/   30]
loss: 0.531543  [   12/   30]
loss: 0.530586  [   16/   30]
loss: 0.527204  [   20/   30]
loss: 0.520662  [   24/   30]
loss: 0.516456  [   28/   30]
loss: 0.513351  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.44812226 
 IoU: 0.991667 
 F1: nan 

test Error: 
 Avg loss: 0.44927553 
 IoU: 0.990904 
 F1: nan 

loss: 0.509793  [    4/   30]
loss: 0.507545  [    8/   30]
loss: 0.501706  [   12/   30]
loss: 0.498341  [   16/   30]
loss: 0.491947  [   20/   30]
loss: 0.492344  [   24/   30]
loss: 0.489733  [   28/   30]
loss: 0.486763  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:228: RuntimeWarning: invalid value encountered in scalar divide
  F1 = 2 * (precision * recall) / (precision + recall)
validation Error: 
 Avg loss: 0.41126668 
 IoU: 0.991676 
 F1: nan 

test Error: 
 Avg loss: 0.40899276 
 IoU: 0.990903 
 F1: nan 

