Traceback (most recent call last):
  File "/home/matevz/miniforge3/envs/ipad/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/matevz/miniforge3/envs/ipad/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matevz/Desktop/Diplomska/Framework/Work/zzzzz_runners_simple/sclera/segnet/y_train.py", line 29, in <module>
    run(command, **get_novel_out_and_err(out_folder_path))
  File "/home/matevz/Desktop/Diplomska/Framework/Work/sysrun/helpers/help.py", line 79, in run
    stdout, stderr = process.communicate(input=input) # also waits for process to terminate
  File "/home/matevz/miniforge3/envs/ipad/lib/python3.9/subprocess.py", line 1126, in communicate
    self.wait()
  File "/home/matevz/miniforge3/envs/ipad/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/home/matevz/miniforge3/envs/ipad/lib/python3.9/subprocess.py", line 1933, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/matevz/miniforge3/envs/ipad/lib/python3.9/subprocess.py", line 1891, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
